server:
  port: 8084
  ssl:
    key-store-type: PKCS12
    key-store: path
    key-store-password: password
    key-alias: alias
    enabled: false

iam:
  api:
    base:
      url: http://localhost:8081/api
